name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
        else
          echo "gradlew not found in root, checking app folder..."
          if [ -f "./app/gradlew" ]; then
            chmod +x ./app/gradlew
          fi
        fi
        
    - name: Build Debug APK
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug
        elif [ -f "./app/gradlew" ]; then
          cd app && ./gradlew assembleDebug
        else
          echo "No gradlew found!"
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: wood-detection-apk
        path: |
          app/build/outputs/apk/debug/*.apk
          */build/outputs/apk/debug/*.apk
